/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EcolesRouteImport } from './routes/ecoles'
import { Route as GlossaireRouteImport } from './routes/glossaire'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as EquipementsIndexRouteImport } from './routes/equipements.index'
import { Route as EquipementsEquipementRouteImport } from './routes/equipements.$equipement'
import { Route as OperationsIndexRouteImport } from './routes/operations.index'
import { Route as OperationsOperationRouteImport } from './routes/operations.$operation'
import { Route as OrganisationIndexRouteImport } from './routes/organisation.index'
import { Route as OrganisationRegimentRouteImport } from './routes/organisation.$regiment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EcolesRoute = EcolesRouteImport.update({
  id: '/ecoles',
  path: '/ecoles',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaireRoute = GlossaireRouteImport.update({
  id: '/glossaire',
  path: '/glossaire',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipementsIndexRoute = EquipementsIndexRouteImport.update({
  id: '/equipements/',
  path: '/equipements/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipementsEquipementRoute = EquipementsEquipementRouteImport.update({
  id: '/equipements/$equipement',
  path: '/equipements/$equipement',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsOperationRoute = OperationsOperationRouteImport.update({
  id: '/$operation',
  path: '/$operation',
  getParentRoute: () => OperationsRoute,
} as any)
const OrganisationIndexRoute = OrganisationIndexRouteImport.update({
  id: '/organisation/',
  path: '/organisation/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationRegimentRoute = OrganisationRegimentRouteImport.update({
  id: '/organisation/$regiment',
  path: '/organisation/$regiment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecoles': typeof EcolesRoute
  '/glossaire': typeof GlossaireRoute
  '/grades': typeof GradesRoute
  '/operations': typeof OperationsRouteWithChildren
  '/equipements/$equipement': typeof EquipementsEquipementRoute
  '/operations/$operation': typeof OperationsOperationRoute
  '/organisation/$regiment': typeof OrganisationRegimentRoute
  '/equipements/': typeof EquipementsIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/organisation/': typeof OrganisationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecoles': typeof EcolesRoute
  '/glossaire': typeof GlossaireRoute
  '/grades': typeof GradesRoute
  '/equipements/$equipement': typeof EquipementsEquipementRoute
  '/operations/$operation': typeof OperationsOperationRoute
  '/organisation/$regiment': typeof OrganisationRegimentRoute
  '/equipements': typeof EquipementsIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/organisation': typeof OrganisationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ecoles': typeof EcolesRoute
  '/glossaire': typeof GlossaireRoute
  '/grades': typeof GradesRoute
  '/operations': typeof OperationsRouteWithChildren
  '/equipements/$equipement': typeof EquipementsEquipementRoute
  '/operations/$operation': typeof OperationsOperationRoute
  '/organisation/$regiment': typeof OrganisationRegimentRoute
  '/equipements/': typeof EquipementsIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/organisation/': typeof OrganisationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ecoles'
    | '/glossaire'
    | '/grades'
    | '/operations'
    | '/equipements/$equipement'
    | '/operations/$operation'
    | '/organisation/$regiment'
    | '/equipements/'
    | '/operations/'
    | '/organisation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ecoles'
    | '/glossaire'
    | '/grades'
    | '/equipements/$equipement'
    | '/operations/$operation'
    | '/organisation/$regiment'
    | '/equipements'
    | '/operations'
    | '/organisation'
  id:
    | '__root__'
    | '/'
    | '/ecoles'
    | '/glossaire'
    | '/grades'
    | '/operations'
    | '/equipements/$equipement'
    | '/operations/$operation'
    | '/organisation/$regiment'
    | '/equipements/'
    | '/operations/'
    | '/organisation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcolesRoute: typeof EcolesRoute
  GlossaireRoute: typeof GlossaireRoute
  GradesRoute: typeof GradesRoute
  OperationsRoute: typeof OperationsRouteWithChildren
  EquipementsEquipementRoute: typeof EquipementsEquipementRoute
  OrganisationRegimentRoute: typeof OrganisationRegimentRoute
  EquipementsIndexRoute: typeof EquipementsIndexRoute
  OrganisationIndexRoute: typeof OrganisationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecoles': {
      id: '/ecoles'
      path: '/ecoles'
      fullPath: '/ecoles'
      preLoaderRoute: typeof EcolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossaire': {
      id: '/glossaire'
      path: '/glossaire'
      fullPath: '/glossaire'
      preLoaderRoute: typeof GlossaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipements/': {
      id: '/equipements/'
      path: '/equipements'
      fullPath: '/equipements/'
      preLoaderRoute: typeof EquipementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipements/$equipement': {
      id: '/equipements/$equipement'
      path: '/equipements/$equipement'
      fullPath: '/equipements/$equipement'
      preLoaderRoute: typeof EquipementsEquipementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/': {
      id: '/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/$operation': {
      id: '/operations/$operation'
      path: '/$operation'
      fullPath: '/operations/$operation'
      preLoaderRoute: typeof OperationsOperationRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/organisation/': {
      id: '/organisation/'
      path: '/organisation'
      fullPath: '/organisation/'
      preLoaderRoute: typeof OrganisationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisation/$regiment': {
      id: '/organisation/$regiment'
      path: '/organisation/$regiment'
      fullPath: '/organisation/$regiment'
      preLoaderRoute: typeof OrganisationRegimentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OperationsRouteChildren {
  OperationsOperationRoute: typeof OperationsOperationRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsOperationRoute: OperationsOperationRoute,
  OperationsIndexRoute: OperationsIndexRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcolesRoute: EcolesRoute,
  GlossaireRoute: GlossaireRoute,
  GradesRoute: GradesRoute,
  OperationsRoute: OperationsRouteWithChildren,
  EquipementsEquipementRoute: EquipementsEquipementRoute,
  OrganisationRegimentRoute: OrganisationRegimentRoute,
  EquipementsIndexRoute: EquipementsIndexRoute,
  OrganisationIndexRoute: OrganisationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
